---

- name: Check for Existing Repo
  stat: path={{ nexcess_repo_file }}
  register: nexcess_repo_file_result

- name: Install the Nexcess Repo
  template:
    src="nexcess.repo.j2"
    dest="{{ nexcess_repo_file }}"
    owner=root
    group=root
    mode=0644
  when: not nexcess_repo_file_result.stat.exists

- name: Import the Nexcess GPG Key
  rpm_key:
    key: "{{ nexcess_repo_gpg_key_url }}"
    state: present
  when: not nexcess_repo_file_result.stat.exists
