---

- name: Install the Nexcess Repo
  template:
    src="nexcess.repo.j2"
    dest="{{ nexcess_repo_file }}"
    owner=root
    group=root
    mode=0644

- name: Import the Nexcess GPG Key
  rpm_key:
    key: "{{ nexcess_repo_gpg_key_url }}"
    state: present
